version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
      nodejs: 18
    commands:
      - echo Installing system dependencies...
      - apt-get update
      - apt-get install -y git unzip libpng-dev libjpeg-dev libfreetype6-dev libonig-dev libxml2-dev zip curl
      - echo Installing PHP extensions...
      - docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
      - docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd
      - echo Installing PHP dependencies...
      - composer clear-cache
      - composer install --no-interaction --prefer-dist --optimize-autoloader --verbose
      - echo Installing Node.js dependencies...
      - npm install
      - echo Installing Docker...
      - apt-get update
      - apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - apt-get update
      - apt-get install -y docker-ce

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin <your-account-id>.dkr.ecr.<your-region>.amazonaws.com)
      - echo Build started on `date`

  build:
    commands:
      - echo Building the Docker image...
      - docker-compose -f docker-compose.yml build laravel-app
      - echo Tagging the Docker image...
      - docker tag laravel-inertia-app:latest <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/prod-laravel-inertia-image:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/prod-laravel-inertia-image:latest
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
